pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='pages-home'),
    path('explore/<int:id>', views.explore, name='pages-explore'),
]

shreddit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from chord_progressions import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', user_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('pages.urls')),
    path('chord-progressions/', include('chord_progressions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from os import path

import PIL


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


def get_upload_path(instance, filename):

    extension = filename.split('.')[-1]

    upload_path = path.join(f"profile_images/{instance.email}/", f'profile_image.{extension}')
    return upload_path


class CustomUser(AbstractUser):
    username = None

    # _('verbose_name') translates the verbose_name into the user's language
    email = models.EmailField(_("email address"), unique=True)

    profile_image = models.ImageField(
        _("profile image"),
        default="profile_images/default.jpg",
        upload_to=get_upload_path,
    )
    date_joined = models.DateField(_("date joined"), auto_now_add=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        return self.email


# class Profile(models.Model):
#     user        = models.OneToOneField(User, on_delete=models.CASCADE)
#     avatar      = models.ImageField(default='default.jpg', upload_to='avatars')

#     def __str__(self):
#         return f'{self.user.username}\'s profile'

#     def save(self, *args, **kwargs):
#         super().save()

#         img = Image.open(self.avatar.path)

#         if img.height > 500 or img.width > 500:
#             output_size = (500,500)
#             img.thumbnail(output_size)
#             img.save(self.avatar.path)

# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_profile(sender, instance, **kwargs):
#     instance.profile.save()

# class CustomUser(AbstractUser):
#     email       = models.EmailField(max_length=50, unique=True)
#     username    = models.CharField(max_length=20, unique=True)
#     date_joined = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.username

users/forms.py
from django import forms
from users.models import CustomUser
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['profile_image']

class ProfileImageUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['profile_image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserSignupForm, UserUpdateForm, ProfileImageUpdateForm
from chord_progressions.models import ChordProgression
from .models import CustomUser
import json
from PIL import Image
from os import mkdir
from os import path, remove
from shutil import move
from django.conf import settings


def signup(request):
    if request.method == "POST":
        form = UserSignupForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Account created! You can now login as {username}!"
            )
            return redirect("login")
        else:
            print(form.errors)
    else:
        form = UserSignupForm()

    return render(request, "users/signup.html", {"form": form})


@login_required
def profile(request):

    print(request.user.profile_image.url)

    if request.method == "POST":

        u_form = UserUpdateForm(
            data=request.POST, instance=request.user, files=request.FILES
        )
        old_extension = request.user.profile_image.url.split(".")[-1]

        if u_form.is_valid():
            # if an image was uploaded,
            # resize if greater than 500px, 500px
            if request.FILES:
                old_file_name = request.user.profile_image.url

                old_image_path = path.join(
                    settings.MEDIA_ROOT,
                    "profile_images",
                    request.user.email,
                    f"profile_image.{old_extension}".lower(),
                )

                # delete old profile_image if it exists
                if path.isfile(old_image_path):
                    remove(old_image_path)

                img_file = request.FILES.get("profile_image")
                img_name = img_file.name
                img = Image.open(img_file)
                img_extension = img_name.split(".")[-1]
                # print(img_extension)
                img_path = path.join(
                    settings.MEDIA_ROOT, "profile_images", request.user.email
                )

                print('IMAGE PATH: ',  img_path)

                if img.height > 500 or img.width > 500:
                    output_size = (500, 500)
                    img.thumbnail(output_size)

                # rename image
                renamed_path = path.join(
                    img_path, f"profile_image.{img_extension.lower()}"
                )

                print('RENAMED PATH: ', renamed_path)

                # save original path
                img.save(renamed_path)

                # request.user.profile_image = path.join(img_path, img_name)
                u_form.save()

                print('IMG NAME: ', img_name)
                print('IMAGE PATH AND NAME: ', path.join(img_path, img_name))
                # remove original photo after upload
                # remove(path.join(img_path, img_name))
            messages.success(request, f"Your account has been updated!")
            return redirect("profile")
        else:
            errors = u_form.errors
            print(errors)
    else:
        progressions = ChordProgression.objects.filter(creator=request.user)

        # print(f'progressions*** {progressions}')

        u_form = UserUpdateForm(instance=request.user)

    context = {
        "u_form": u_form,
        "progressions": progressions,
    }
    return render(request, "users/profile.html", context)

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div id="login-content" class="blue-grey">
        <h1>Login</h1>

        <div class="row">
            <div class="col s12 form-container">
                <form method="POST" class="login-form">
                    {% csrf_token %}
                    
                    <fieldset>
                        {{ form }}
                    </fieldset>
        
                    <div class="form-submit">
                        <button class="submit-button blue-grey darken-2 blue-grey-text text-lighten-4" type="submit">Login</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="register-links">
            <small class="nav-link">Need an account? <a href="{% url 'signup' %}">Sign Up</a></small><br/>
            <small class="nav-link">Forgot password? <a href="#" >Reset</a></small>
        </div>
    </div>

{% endblock %}

templates/users/logout.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="blue-text text-darken-2">You have been logged out</h1>

        <div class="signup-links">
            <small><a href="{% url 'login' %}">Login again</a></small><br/>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
    <div id="profile-content" class="blue-grey">
        <div class="row">
            <div class="col s12 avatar-container">
                <div class="avatar">
                    <img class=""
                        src="{{ user.profile_image.url }}" 
                        alt="{{ user.email }}" />
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col s12 center">
                <div class="username-display">
                    <h1>{{ user.email }}</h1>
                    <p><small>Joined:</small><br/>{{ user.date_joined }}</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col s8 offset-s2 l12 center">
                <div class="update-form center">
                    <form method="POST" enctype="multipart/form-data"> 
                        {% csrf_token %}
                        
                        <label for="id_profile_image" id="profile-image-field-label">
                            <p class="blue-grey darken-2 blue-grey-text text-lighten-5">
                                Select profile image
                            </p> 
                            <div id="profile-image-field">
                                {{ u_form.profile_image }}
                            </div>
                        </label>
                        <div id="new-image">
                            No file selected
                        </div>

                            <button type="submit" 
                                class="submit-button 
                                blue-grey
                                darken-2
                                blue-grey-text
                                text-lighten-5">
                            Update
                            </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="row chord-progressions">
            <div class="col s12 l12">
                <h1>Saved Progressions</h1>
    
                {% for progression in progressions %}
                    <div class="row center">
                        <div class="col s12 l12 saved-progression-container">
                            <div class="card">
                                <div class="card-content blue-grey lighten-2">
                                    <div class="title activator blue-grey lighten-3 text-darken-4">
                                        <span class="hide-on-large-only">{{ progression|truncatechars:20 }}</span>
                                        <span class="hide-on-med-and-down">{{ progression|truncatechars:40 }}</span>
                                        <i class="material-icons right">more_vert</i>
                                    </div>
                                </div>
                                <div class="card-reveal blue-grey lighten-2">
                                    <div class="row card-links">
                                        <div class="col s2 l2"></div>
                                        <div class="col s4 l4">
                                            <div class="card-link blue-grey darken-1 nav-link">
                                                <a href="{% url 'pages-explore' id=progression.id %}">Explore</a>
                                            </div>
                                        </div>
                                        <div class="col s4 l4">
                                            <div class="card-link blue-grey darken-1 nav-link">
                                                <a href="{% url 'delete-progression' id=progression.id %}">Delete</a>
                                            </div>
                                        </div>
                                        <div class="col s2 l2">
                                            <span class="card-title"><i class="material-icons right close blue-grey-text text-darken-4">close</i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                {% empty %}
                    <p>No progressions yet</p>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
    <div id="signup-content" class="blue-grey">
        <div class="row">
            <div class="col s12 center">
                <h1>Shreddit.io</h1>
                <h2>Sign up</h2>
            </div>
        </div>
        <div class="row">
            <div class="col s10 offset-s1">
                <div class="signup-form">
                    <form method="POST">
                        {% csrf_token %}
            
                        <fieldset>
                            {{ form.as_p }}
                        </fieldset>

                        <div class="row">
                            <div class="col s12">
                                <div class="form-submit">
                                    <button class="submit-button blue-grey darken-2 blue-grey-text text-lighten-4" type="submit">Sign Up!</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col s12">
                <div class="signup-links">
                    <small class="nav-link">Already have an account? <a href="{% url 'login' %}">Sign In</a></small><br/>
                    <small class="nav-link">Forgot password? <a href="#">Reset</a></small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}